# generate json files about data from different sources
# Then create pdf from it

from reportlab.pdfgen import canvas
from reportlab.graphics.charts.piecharts import Pie
import logging
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import A4, LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm, cm
from reportlab.platypus import *
from reportlab.rl_config import defaultPageSize
from reportlab.lib.colors import HexColor
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import *
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.charts.textlabels import Label
from datetime import date
from math import floor, ceil

from gather_info import *


fields = []
styles = getSampleStyleSheet()
ParaStyle = styles["Normal"]
WIDTH = defaultPageSize[0]
HEIGHT = defaultPageSize[1]


#CommonData adds page number and header to every page at the footer on bottom right corner
class CommonData(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        """add page info to each page (page x of y)"""
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            self.add_logo()
            self.drawString(5, HEIGHT-70, "VSS - Security Overview Report")
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.setFont("Helvetica", 7)
        self.drawRightString(200*mm, 20*mm,
            "Page %d of %d" % (self._pageNumber, page_count))
    
    def add_logo(self):
        self.drawImage("images/vmware_logo.jpg", 20*mm, 20*mm, width=1.5*inch, height=0.24*inch)


# Add VSS image on the first page. Cna be replaced with custom image by providing the file in same location.
# Try to use a ".jpeg" image
def on_first_page(canvas, doc):
    canvas.saveState()
    canvas.drawImage("images/vss.jpeg", 20*mm, HEIGHT-200,width=6.5*inch, height=1.06*inch)
    canvas.setFont('Times-Bold', 20)
    canvas.drawCentredString(WIDTH/2.0, HEIGHT - 350, "Security Overview Report")
    canvas.setFont('Times-Roman', 14)
    company = get_org_name()
    canvas.drawCentredString(WIDTH/2.0, HEIGHT/2.0-(100), "For: " + company)
    canvas.setFillColor(HexColor("#696969"))
    canvas.setFont('Times-Roman', 12)
    today = date.today()
    today_formatted = today.strftime("%b-%d-%Y")
    canvas.drawCentredString(WIDTH/2.0, HEIGHT/2.0-(120), "Generated On: " + today_formatted)
    canvas.restoreState()
        
def add_para(txt, doc, style=ParaStyle, klass=Paragraph, sep=0.1):
    s = Spacer(0, sep*inch)
    para = klass(txt, style)
    sect = [s, para]
    result = KeepTogether(sect)
    return result


# Adds Exectuive summary section
def add_executive_summary_section(document):
    
    fields.append(Paragraph("Executive Summary", style=styles["Heading1"]))
    fields.append(Paragraph("1. Introduction", style=styles["Heading3"]))
    account_info = get_account_info()
    text = '''This report contains cloud configuration security assessment results from the of ''' + str(account_info["accounts"]) + ''' cloud accounts across your environment. 
    The cloud environment was evaluated across ''' + str(account_info["rules"]) + ''' rules associated with ''' + str(account_info["compliance_frameworks"]) + ''' compliance frameworks. 
    There were ''' + str(account_info["total_violations"]) + ''' violations found.<br/><br/> 
    
    This analysis provides summaries and breakdowns to help address the risk identified, along with change comparison since last evaluation. 
    The findings are generated by comprehensive evaluation through a revolutionary inter-connected security model that identifies in-depth configuration problems.'''
    
    info = add_para(text, document)
    fields.append(info)

def add_scope_section(document):
    fields.append(Paragraph("2. Scope", style=styles["Heading3"]))
    config = get_config()
    
    text = '''
    The scope of this report is within the context of the following filters:<br/>
    Provider: 		AWS, Azure<br/>
    Cloud Accounts: All 	(472 accounts)<br/>
    Frameworks: 	All 	(9 frameworks)<br/>
    Severity: 		High<br/>
    Cloud Tag: 		All<br/>
    Environment:	All<br/>
    '''
    info = add_para(text, document)
    fields.append(info)


def add_findings_by_provider_chart(document):
    drawing = Drawing(300, 200)
    data = get_findings_by_provider()
    if(data[0][0] > data[0][1]):
        maxVal = data[0][0]
    else:
        maxVal = data[0][1]
    
    bar = HorizontalBarChart()
    bar.x = 30
    bar.y = 0
    bar.height = 150
    bar.width = 400
    bar.data = data
    bar.strokeColor = colors.white
    bar.valueAxis.valueMin = 0
    bar.valueAxis.valueMax = maxVal*2   ## graph displa twice as much as max violation
    bar.valueAxis.valueStep = int(ceil(maxVal/400))*100  ## Convert to neartest 100
    bar.categoryAxis.labels.boxAnchor = 'ne'
    bar.categoryAxis.labels.dx = -10
    bar.categoryAxis.labels.dy = -2
    bar.categoryAxis.labels.fontName = 'Helvetica'
    bar.categoryAxis.categoryNames = ["AWS", "Azure"]
    bar.bars[(0,0)].fillColor = HexColor("#f5990f")
    bar.bars[(0,1)].fillColor = HexColor("#3a32a8")
    bar.barWidth = 10
    bar.barSpacing = 0.1
    bar.barLabelFormat = '%d'
    bar.barLabels.nudge = 15

    drawing.add(bar)
  #  add_legend(drawing, bar)
    yLabel = Label()
    yLabel.setText("Number of Findings ---->")
    yLabel.fontSize = 12
    yLabel.fontName = 'Helvetica'
    yLabel.dx = 250
    yLabel.dy = -30
    
    chartLabel = Label()
    chartLabel.setText("Findings by Provider")
    chartLabel.fontSize = 14
    chartLabel.fontName = 'Helvetica'
    chartLabel.dx = 250
    chartLabel.dy = 160
    
    drawing.add(chartLabel)
    drawing.add(yLabel)
    fields.append(drawing)


def add_cloud_security_overview_section(document):
    fields.append(Paragraph("3. Cloud Security Overview", style=styles["Heading3"]))
    fields.append(add_para("<br/><br/>", document))
    data = [("Cloud Accounts", 472), ("Open Findings", 1212), ("Resolved Findings", 342), ("Rules Configured", 250),
            ("High Severity Findings", 100), ("Compliance Frameworks", 9)]
    b = Table(data, 150, 30)
    b.hAlign = "CENTER"
    b.vAlign = "MIDDLE"
    b.setStyle(TableStyle([   
                       ('BACKGROUND', (-1,0), (-1, -1), HexColor("#3498eb")),
                       ('GRID',(0,0),(-1,-1),0.01*inch,(0,0,0,)),
                       ('FONT', (0,0), (-1,-1), 'Helvetica')]))
    fields.append(b)
    add_findings_by_provider_chart(doc)


def add_cloud_account_risk_overview_section(document):
    fields.append(Paragraph("4. Risk Overview", style=styles["Heading3"]))
    fields.append(Paragraph("4.1 Cloud Account Risk Overview", style=styles["Heading4"]))
    open_resolve = get_open_resolved_findings()
    account_info = get_account_info()
    text = ''' There are ''' + str(open_resolve["open"]) + ''' open findings and ''' + str(open_resolve["resolved"]) + ''' resolved findings across ''' + str(account_info["accounts"]) + ''' accounts.
    '''
    fields.append(add_para(text, document))
    add_findings_by_account_chart(document)

def add_findings_by_account_chart(document):
    drawing = Drawing(500, 500)
    findings, accounts = get_top_10_accounts_by_findings()
    
    bar = HorizontalBarChart()
    bar.x = 25
    bar.y = -10
    bar.height = 500
    bar.width = 450
    bar.data = findings
    bar.strokeColor = colors.white
    bar.valueAxis.valueMin = 0
    bar.valueAxis.valueMax = 1000*1.5   ## graph displa twice as much as max violation
    bar.valueAxis.valueStep = int(ceil(1000/400))*100  ## Convert to neartest 100
    bar.categoryAxis.labels.boxAnchor = 'ne'
    bar.categoryAxis.labels.dx = -10
    bar.categoryAxis.labels.dy = -2
    bar.categoryAxis.labels.fontName = 'Helvetica'
    bar.categoryAxis.categoryNames = accounts
    bar.bars[0].fillColor = HexColor("#3a32a8")
    bar.bars[1].fillColor = colors.gray
    bar.barWidth = 5
    bar.barSpacing = 0.5
    bar.barLabelFormat = '%d'
    bar.barLabels.nudge = 15
    
    drawing.add(bar)
    fields.append(drawing)
    newPage()
    

def newPage():
    fields.append(PageBreak())

# Creates the initial report document
def init_report():
    doc = SimpleDocTemplate("vss_compliance_report.pdf", pagesize=LETTER)
    return doc

def build_report(document):
    document.build(fields, onFirstPage=on_first_page, canvasmaker=CommonData)
    logging.info("Successfully generated report !!")

if __name__ == '__main__':
    logging.getLogger().setLevel(logging.INFO)
    logging.info("Generating Report ...")
    doc = init_report()
    newPage()
    add_executive_summary_section(doc)
    add_scope_section(doc)
    newPage()
    add_cloud_security_overview_section(doc)
    newPage()
    add_cloud_account_risk_overview_section(doc)
    newPage()
    build_report(doc)
   
   